---
- project:
    check:
      jobs:
        - fi-tox-mypy:
            vars:
              dependencies:
                - libffi-devel
        - fi-tox-lint:
            vars:
              dependencies:
                - libffi-devel
        - fi-tox-format:
            vars:
              dependencies:
                - libffi-devel
        - fi-tox-python310
        - fi-tox-python311
        - fi-tox-python312
        - fi-tox-docs:
            vars:
              dependencies:
                - graphviz
                - python3-sphinxcontrib-httpdomain
                - python3-sqlalchemy_schemadisplay
                - libffi-devel
        - fi-tox-bandit:
            vars:
              dependencies:
                - libffi-devel
        - fi-tox-diff-cover:
            vars:
              tox_envlist: "py312,diff-cover"
              dependencies:
                - libffi-devel
              job_dependencies: "python312"
